included:
  - Sources
  - App
excluded:
  - "**/*/Package.swift"
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - implicit_return
  - legacy_multiple
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
disabled_rules:
  - nesting
  - todo
  - line_length
  - opening_brace
  - large_tuple
  - void_function_in_ternary

force_cast: warning
force_try: warning

type_body_length:
  - 600 # warning
  - 700 # error

generic_type_name:
  warning: 45
  error: 50

function_body_length:
  warning: 60

attributes:
  attributes_with_arguments_always_on_line_above: false

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

trailing_comma:
  mandatory_comma: true

type_name:
  excluded:
    - ID

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded: # excluded via string array
    - id
    - URL

cyclomatic_complexity:
  ignores_case_statements: true